# Generated by Django 4.1.3 on 2022-12-12 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(choices=[('SELECT', 'Select'), ('PROFESSOR', 'Professor'), ('ASSOCIATE PROFESSOR', 'Associate Professor'), ('ASSTISTANT PROFESSOR', 'Asstistant Professor'), ('DOCTOR', 'Doctor'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='Select', max_length=25)),
                ('university', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.CreateModel(
            name='AssociateEditor',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.relate')),
            ],
            bases=('Main.relate',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.relate')),
            ],
            bases=('Main.relate',),
        ),
        migrations.CreateModel(
            name='MainEditor',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.relate')),
            ],
            bases=('Main.relate',),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.relate')),
            ],
            bases=('Main.relate',),
        ),
    ]
