# Generated by Django 4.1.4 on 2023-05-30 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_verified_user_created_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(choices=[('Select', 'Select'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Asstistant Professor'), ('Dr.', 'Dr'), ('Lecturer', 'Lecturer'), ('Student', 'Student')], default='Select', max_length=25)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.relate')),
                ('is_author_accepted', models.BooleanField(default=False)),
            ],
            bases=('main.relate',),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.relate')),
                ('is_associate_editor_accepted', models.BooleanField(default=False)),
                ('is_main_editor_accepted', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=1000)),
            ],
            bases=('main.relate',),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('relate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.relate')),
                ('is_reviewer_accepted', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=1000)),
            ],
            bases=('main.relate',),
        ),
    ]
