# Generated by Django 4.1.3 on 2022-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_relate_rename_gender_user_gender_user_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relate',
            old_name='university',
            new_name='institution',
        ),
        migrations.AddField(
            model_name='relate',
            name='is_ass_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relate',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relate',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relate',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
