# Generated by Django 4.1.3 on 2022-12-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_university_relate_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
