# Generated by Django 4.1.3 on 2022-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Verified',
            field=models.BooleanField(default=True),
        ),
    ]
