# Generated by Django 4.1.3 on 2022-12-26 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_user_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relate',
            name='is_ass_editor',
        ),
        migrations.RemoveField(
            model_name='relate',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='relate',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='relate',
            name='is_reviewer',
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='is_ass_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maineditor',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relate',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
