# Generated by Django 4.1.3 on 2022-12-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_relate_is_ass_editor_remove_relate_is_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relate',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relate',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='relate',
            name='mobile',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='relate',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
