# Generated by Django 4.1.3 on 2022-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_relate_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associateeditor',
            name='is_ass_editor',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='maineditor',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='is_reviewer',
        ),
        migrations.AddField(
            model_name='relate',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
