# Generated by Django 4.1.3 on 2022-12-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_relate_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relate',
            name='accepted',
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='is_associate_editor_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_author_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maineditor',
            name='is_main_editor_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_reviewer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
