# Generated by Django 4.1.3 on 2022-12-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_associateeditor_maineditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associateeditor',
            name='relate_ptr',
        ),
        migrations.RemoveField(
            model_name='maineditor',
            name='relate_ptr',
        ),
        migrations.DeleteModel(
            name='AssociateEditor',
        ),
        migrations.DeleteModel(
            name='MainEditor',
        ),
    ]
