# Generated by Django 4.1.3 on 2022-12-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_editor_domain_editor_subdomain_reviewer_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='area',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='area',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editor',
            name='subdomain',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='subdomain',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
