# Generated by Django 4.1.4 on 2023-05-30 18:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Papers_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=600)),
                ('abstract', models.CharField(max_length=4200)),
                ('keywords', models.CharField(max_length=4200)),
                ('authors_name', models.CharField(max_length=3105)),
                ('corres_emails', models.CharField(max_length=300, null=True)),
                ('version', models.IntegerField(default=0)),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('reference_number', models.CharField(max_length=30)),
                ('reference_url', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('paper_type', models.IntegerField(choices=[(0, 'Select'), (1, 'Research'), (2, 'Review')])),
                ('manuscript_pdf', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('cover_letter_pdf', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('supplimentary_file', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publish_Papers_Info',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=337)),
                ('doi', models.CharField(default='Null', max_length=59, null=True)),
                ('pmcid', models.CharField(default='Null', max_length=10, null=True)),
                ('pubmed_id', models.IntegerField(default=0, null=True)),
                ('licensee', models.CharField(default='Null', max_length=11, null=True)),
                ('abstract', models.CharField(max_length=4127)),
                ('publish_time', models.DateField(default=datetime.datetime.now)),
                ('authors', models.CharField(max_length=3105)),
                ('journal', models.CharField(max_length=55)),
                ('pdf_json_files', models.CharField(default='Null', max_length=430, null=True)),
                ('pmc_json_files', models.CharField(default='Null', max_length=44, null=True)),
                ('url', models.CharField(max_length=87)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Update_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=600)),
                ('abstract', models.CharField(max_length=4200)),
                ('keywords', models.CharField(max_length=4200)),
                ('authors_name', models.CharField(max_length=3105)),
                ('corres_emails', models.CharField(max_length=300, null=True)),
                ('version', models.IntegerField(default=0)),
                ('paper_type', models.IntegerField(choices=[(0, 'Select'), (1, 'Research'), (2, 'Review')])),
                ('manuscript_pdf', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('cover_letter_pdf', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('supplimentary_file', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(blank=True, max_length=200, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journals.submit_papers_info')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('review_status', models.CharField(default='No Decision', max_length=100)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper_editor', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journals.submit_papers_info')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journals.submit_papers_info')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.TextField()),
                ('version', models.IntegerField(default=0)),
                ('supplimentary_file', models.FileField(blank=True, null=True, upload_to='papers_file/comments_file/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.submit_papers_info')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articles_Papers_Info',
            fields=[
                ('uid', models.DecimalField(decimal_places=3, max_digits=7, primary_key=True, serialize=False)),
                ('submitter', models.CharField(default='Null', max_length=34, null=True)),
                ('authors', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=400)),
                ('comments', models.CharField(default='Null', max_length=600, null=True)),
                ('journal', models.CharField(max_length=250)),
                ('doi', models.CharField(default='Null', max_length=150, null=True)),
                ('categories', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=4500)),
                ('versions', models.CharField(default='Null', max_length=1000, null=True)),
                ('publish_time', models.DateField(default=datetime.datetime.now)),
                ('authors_parsed', models.CharField(default='Null', max_length=2000, null=True)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
