# Generated by Django 4.1.3 on 2022-12-12 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles_papers_info',
            fields=[
                ('uid', models.DecimalField(decimal_places=3, max_digits=7, primary_key=True, serialize=False)),
                ('submitter', models.CharField(default='Null', max_length=34, null=True)),
                ('authors', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=400)),
                ('comments', models.CharField(default='Null', max_length=600, null=True)),
                ('journal', models.CharField(max_length=250)),
                ('doi', models.CharField(default='Null', max_length=150, null=True)),
                ('categories', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=4500)),
                ('versions', models.CharField(default='Null', max_length=1000, null=True)),
                ('publish_time', models.DateField(default=datetime.datetime.now)),
                ('authors_parsed', models.CharField(default='Null', max_length=2000, null=True)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('SELECT', 'Select'), ('PHYSICAL SCIENCES AND ENGINNERING', 'Physical Sciences And Enginnering'), ('LIFE SCIENCES', 'Life Sciences'), ('HEALTH SCIENCES', 'Health Sciences'), ('SOCIAL SCIENCES AND HUMANITIES', 'Social Sciences And Humanities'), ('UNKOWN', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(default='UNKNOWN', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='papers_info',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sha', models.CharField(default='Null', max_length=250, null=True)),
                ('source_x', models.CharField(default='Null', max_length=3, null=True)),
                ('title', models.CharField(max_length=337)),
                ('doi', models.CharField(default='Null', max_length=59, null=True)),
                ('pmcid', models.CharField(default='Null', max_length=10, null=True)),
                ('pubmed_id', models.IntegerField(default='Null', null=True)),
                ('licensee', models.CharField(default='Null', max_length=11, null=True)),
                ('abstract', models.CharField(max_length=4127)),
                ('publish_time', models.DateField(default=datetime.datetime.now)),
                ('authors', models.CharField(max_length=3105)),
                ('journal', models.CharField(max_length=55)),
                ('pdf_json_files', models.CharField(default='Null', max_length=430, null=True)),
                ('pmc_json_files', models.CharField(default='Null', max_length=44, null=True)),
                ('url', models.CharField(max_length=87)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('SELECT', 'Select'), ('PHYSICAL SCIENCES AND ENGINNERING', 'Physical Sciences And Enginnering'), ('LIFE SCIENCES', 'Life Sciences'), ('HEALTH SCIENCES', 'Health Sciences'), ('SOCIAL SCIENCES AND HUMANITIES', 'Social Sciences And Humanities'), ('UNKOWN', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(default='UNKNOWN', max_length=200)),
            ],
        ),
    ]
