# Generated by Django 4.1.3 on 2022-12-12 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_university_relate_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0002_articles_papers_info_user_papers_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_Papers_Info',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=337)),
                ('doi', models.CharField(default='Null', max_length=59, null=True)),
                ('pmcid', models.CharField(default='Null', max_length=10, null=True)),
                ('pubmed_id', models.IntegerField(default='Null', null=True)),
                ('licensee', models.CharField(default='Null', max_length=11, null=True)),
                ('abstract', models.CharField(max_length=4127)),
                ('publish_time', models.DateField(default=datetime.datetime.now)),
                ('authors', models.CharField(max_length=3105)),
                ('journal', models.CharField(max_length=55)),
                ('pdf_json_files', models.CharField(default='Null', max_length=430, null=True)),
                ('pmc_json_files', models.CharField(default='Null', max_length=44, null=True)),
                ('url', models.CharField(max_length=87)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('SELECT', 'Select'), ('PHYSICAL SCIENCES AND ENGINNERING', 'Physical Sciences And Enginnering'), ('LIFE SCIENCES', 'Life Sciences'), ('HEALTH SCIENCES', 'Health Sciences'), ('SOCIAL SCIENCES AND HUMANITIES', 'Social Sciences And Humanities'), ('UNKOWN', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(default='UNKNOWN', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submit_Papers_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=337)),
                ('abstract', models.CharField(max_length=4127)),
                ('authors', models.CharField(max_length=3105)),
                ('journal', models.CharField(max_length=55)),
                ('pdf', models.FileField(null=True, upload_to='papers_file/')),
                ('views', models.IntegerField(default=0)),
                ('download', models.IntegerField(default=0)),
                ('domain', models.CharField(choices=[('SELECT', 'Select'), ('PHYSICAL SCIENCES AND ENGINNERING', 'Physical Sciences And Enginnering'), ('LIFE SCIENCES', 'Life Sciences'), ('HEALTH SCIENCES', 'Health Sciences'), ('SOCIAL SCIENCES AND HUMANITIES', 'Social Sciences And Humanities'), ('UNKOWN', 'Unknown')], default='Select', max_length=200)),
                ('subdomain', models.CharField(default='UNKNOWN', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.relate')),
            ],
        ),
        migrations.CreateModel(
            name='Update_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
            ],
        ),
        migrations.DeleteModel(
            name='papers_info',
        ),
    ]
