# Generated by Django 4.1.3 on 2022-12-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_university_relate_institution_and_more'),
        ('Journals', '0003_publish_papers_info_submit_papers_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update_History',
            new_name='Paper_Update_History',
        ),
        migrations.RenameField(
            model_name='submit_papers_info',
            old_name='authors',
            new_name='authors_name',
        ),
        migrations.RemoveField(
            model_name='submit_papers_info',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='submit_papers_info',
            name='pdf',
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='corres_emails',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='keywords',
            field=models.CharField(default='null', max_length=4200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='paper_type',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='abstract',
            field=models.CharField(max_length=4200),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.author'),
        ),
        migrations.CreateModel(
            name='Paper_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('manuscript_pdf', models.FileField(upload_to='papers_file/')),
                ('cover_letter_pdf', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('supplimentary_file', models.FileField(upload_to='papers_file/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.associateeditor')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
            ],
        ),
    ]
