# Generated by Django 4.1.3 on 2022-12-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0004_rename_update_history_paper_update_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='paper_type',
            field=models.IntegerField(choices=[(0, 'Select'), (1, 'Research'), (2, 'Review')]),
        ),
    ]
