# Generated by Django 4.1.3 on 2022-12-23 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0005_alter_submit_papers_info_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_papers_info',
            name='cover_letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='papers_file/'),
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='manuscript_pdf',
            field=models.FileField(default='ss', upload_to='papers_file/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='supplimentary_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='papers_file/'),
            preserve_default=False,
        ),
    ]
