# Generated by Django 4.1.3 on 2022-12-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0008_alter_submit_papers_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='status',
            field=models.CharField(default='Under Review', max_length=50),
        ),
    ]
