# Generated by Django 4.1.3 on 2022-12-24 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0009_alter_submit_papers_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='manuscript_pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='papers_file/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='supplimentary_file',
            field=models.FileField(default='dss', upload_to='papers_file/'),
            preserve_default=False,
        ),
    ]
