# Generated by Django 4.1.3 on 2022-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0010_alter_submit_papers_info_manuscript_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='manuscript_pdf',
            field=models.FileField(blank=True, null=True, upload_to='papers_file/'),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='supplimentary_file',
            field=models.FileField(blank=True, null=True, upload_to='papers_file/'),
        ),
    ]
