# Generated by Django 4.1.3 on 2022-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0011_alter_submit_papers_info_manuscript_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='status',
            field=models.CharField(default='Submitted', max_length=50),
        ),
    ]
