# Generated by Django 4.1.3 on 2022-12-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0012_alter_submit_papers_info_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_update_history',
            name='created',
        ),
    ]
