# Generated by Django 4.1.3 on 2022-12-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0014_paper_update_history_abstract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_update_history',
            name='comment',
        ),
    ]
