# Generated by Django 4.1.3 on 2022-12-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0015_remove_paper_update_history_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('version', models.IntegerField(default=0)),
                ('supplimentary_file', models.FileField(blank=True, null=True, upload_to='papers_file/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
            ],
        ),
        migrations.AddField(
            model_name='paper_update_history',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Paper_uploads',
        ),
    ]
