# Generated by Django 4.1.3 on 2022-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0016_paper_comments_paper_update_history_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_papers_info',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
