# Generated by Django 4.1.3 on 2022-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0017_submit_papers_info_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_reviewers',
            name='review_status',
            field=models.CharField(default='Not-Assigned', max_length=100),
        ),
    ]
