# Generated by Django 4.1.3 on 2022-12-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0020_alter_publish_papers_info_pubmed_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper_Editors',
        ),
    ]
