# Generated by Django 4.1.3 on 2022-12-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_editor'),
        ('Journals', '0021_delete_paper_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.editor')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Journals.submit_papers_info')),
            ],
        ),
    ]
