# Generated by Django 4.1.3 on 2022-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0022_paper_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='domain',
            field=models.CharField(choices=[('SELECT', 'Select'), ('PHYSICAL SCIENCES AND ENGINNERING', 'Physical Sciences And Enginnering'), ('LIFE SCIENCES', 'Life Sciences'), ('HEALTH SCIENCES', 'Health Sciences'), ('SOCIAL SCIENCES AND HUMANITIES', 'Social Sciences And Humanities'), ('UNKNOWN', 'Unknown')], default='Select', max_length=200),
        ),
    ]
