# Generated by Django 4.1.3 on 2022-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0023_alter_submit_papers_info_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_papers_info',
            name='domain',
            field=models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200),
        ),
        migrations.AlterField(
            model_name='articles_papers_info',
            name='subdomain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper_update_history',
            name='subdomain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='publish_papers_info',
            name='domain',
            field=models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200),
        ),
        migrations.AlterField(
            model_name='publish_papers_info',
            name='subdomain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='domain',
            field=models.CharField(choices=[('Select', 'Select'), ('Physical sciences and engineering', 'Physical Sciences And Engineering'), ('Life sciences', 'Life Sciences'), ('Health sciences', 'Health Sciences'), ('Social sciences and humanities', 'Social Sciences And Humanities'), ('Unknown', 'Unknown')], default='Select', max_length=200),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='subdomain',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
