# Generated by Django 4.1.3 on 2022-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0026_paper_update_history_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_reviewers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles_papers_info',
            name='subdomain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='review_status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper_update_history',
            name='subdomain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publish_papers_info',
            name='subdomain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='subdomain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
