# Generated by Django 4.1.3 on 2022-12-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_editor'),
        ('Journals', '0027_paper_reviewers_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_reviewers',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.editor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='review_status',
            field=models.CharField(default='No Decision', max_length=100),
        ),
    ]
