# Generated by Django 4.1.3 on 2022-12-29 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0028_paper_reviewers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_reviewers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
