# Generated by Django 4.1.3 on 2022-12-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_editor'),
        ('Journals', '0029_alter_paper_reviewers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_reviewers',
            name='user',
        ),
        migrations.AddField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.editor'),
            preserve_default=False,
        ),
    ]
