# Generated by Django 4.1.3 on 2022-12-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_editor'),
        ('Journals', '0030_remove_paper_reviewers_user_paper_reviewers_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_editors',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_editor', to='Main.relate'),
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_editor', to='Main.relate'),
        ),
    ]
