# Generated by Django 4.1.3 on 2022-12-30 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0032_remove_paper_reviewers_editor_paper_reviewers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_reviewers',
            name='user',
        ),
        migrations.AddField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paper_editor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
