# Generated by Django 4.1.3 on 2022-12-31 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_editor_area_reviewer_area_alter_editor_subdomain_and_more'),
        ('Journals', '0033_remove_paper_reviewers_user_paper_reviewers_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_editor', to='Main.editor'),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.author'),
        ),
    ]
