# Generated by Django 4.1.3 on 2022-12-31 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0019_editor_area_reviewer_area_alter_editor_subdomain_and_more'),
        ('Journals', '0034_alter_paper_reviewers_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_editors',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper_editors',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Journals.submit_papers_info'),
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper_editor', to='Main.editor'),
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Journals.submit_papers_info'),
        ),
        migrations.AlterField(
            model_name='paper_reviewers',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.reviewer'),
        ),
        migrations.AlterField(
            model_name='paper_update_history',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Journals.submit_papers_info'),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.author'),
        ),
    ]
