# Generated by Django 4.1.3 on 2022-12-31 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0035_alter_paper_editors_editor_alter_paper_editors_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_reviewers',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submit_papers_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
