# Generated by Django 4.1.3 on 2022-12-31 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0036_alter_paper_reviewers_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_reviewers',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
