# Generated by Django 4.1.3 on 2022-12-31 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journals', '0038_remove_paper_reviewers_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_comments',
            name='reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_comments',
            name='supplimentary_file',
            field=models.FileField(blank=True, null=True, upload_to='papers_file/comments_file/'),
        ),
    ]
