# Generated by Django 4.1.3 on 2022-12-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0039_paper_comments_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
