# Generated by Django 4.1.3 on 2023-01-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0040_alter_paper_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_papers_info',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='submit_papers_info',
            name='reference_number',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
