# Generated by Django 4.1.3 on 2023-01-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0041_submit_papers_info_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_papers_info',
            name='payment',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
    ]
